services:
  app:
    build: .
    container_name: app
    volumes:
      - ./:/app
    environment:
      - name=value
    ports:
      - "3000:3000"
    networks:
      - my_network
  db:
    image: mysql:8.1.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bahar
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongo-data:/data/db
    networks:
      - my_network
volumes:
  db_data:
  mongo-data:
networks:
  my_network:
    driver: bridge